# Generated by Django 4.0.6 on 2022-08-05 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=500)),
                ('tax_number', models.CharField(max_length=100)),
                ('commercial_year', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 12, 55, 59, 464412))),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=900)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('activation_key', models.CharField(blank=True, max_length=150, null=True)),
                ('user_secret_key', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMaster',
            fields=[
                ('group_master_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('is_default_group', models.BooleanField(default=False)),
                ('group_nature', models.CharField(max_length=255)),
                ('pl_affect', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('permission_view', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('permission_create', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('permission_update', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('permission_delete', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(max_length=255)),
                ('voucher_number', models.IntegerField()),
                ('remarks', models.CharField(max_length=1000)),
                ('transaction_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 12, 55, 59, 465411))),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
            ],
        ),
        migrations.CreateModel(
            name='transactionAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_debit_amount', models.IntegerField(default=0)),
                ('account_credit_amount', models.IntegerField(default=0)),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='company.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerMaster',
            fields=[
                ('ledger_master_id', models.AutoField(primary_key=True, serialize=False)),
                ('ledger_name', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
                ('group_under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.groupmaster')),
            ],
        ),
    ]
