# Generated by Django 4.0.6 on 2022-08-05 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 12, 56, 40, 134257)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 12, 56, 40, 135257)),
        ),
    ]
