# Generated by Django 4.0.6 on 2022-08-05 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companies_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 13, 13, 38, 637726)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 13, 13, 38, 639726)),
        ),
    ]
