# Generated by Django 4.0.6 on 2022-08-05 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companies_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 5, 16, 34, 28, 927365)),
        ),
        migrations.AlterField(
            model_name='companies',
            name='registration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 5, 16, 34, 28, 925363)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
