# Generated by Django 4.0.6 on 2022-08-08 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_groupmaster_group_under_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.users'),
        ),
    ]
