# Generated by Django 4.0.6 on 2022-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_transactions_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
